/*
 * pacboost - High-performance Arch Linux package manager frontend.
 * Copyright (C) 2025  compiledkernel-idk and pacboost contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

use anyhow::{Result, anyhow};
use std::fs;
use std::time::Instant;
use console::style;
use indicatif::{ProgressBar, ProgressStyle};
use reqwest::Client;
use std::sync::{Arc, Mutex};
use futures::stream::{self, StreamExt};

pub async fn rank_mirrors(top: usize) -> Result<()> {
    let mirrorlist_path = "/etc/pacman.d/mirrorlist";
    println!("{}", style(":: reading mirrorlist...").bold());
    
    let content = fs::read_to_string(mirrorlist_path)
        .map_err(|e| anyhow!("failed to read mirrorlist: {}", e))?;
        
    let mut mirrors = Vec::new();
    for line in content.lines() {
        if line.trim().starts_with("Server =") {
            if let Some(url) = line.split('=').nth(1) {
                mirrors.push(url.trim().to_string());
            }
        }
    }
    
    if mirrors.is_empty() {
        return Err(anyhow!("no mirrors found in {}", mirrorlist_path));
    }
    
    println!("{}", style(format!( ":: ranking {} mirrors...", mirrors.len())).bold());
    
    let pb = ProgressBar::new(mirrors.len() as u64);
    pb.set_style(ProgressStyle::default_bar()
        .template("{spinner:.green} [{elapsed_precise}] [{bar:40.cyan/blue}] {pos}/{len} ({eta})")
        .unwrap()
        .progress_chars("#>-"));
        
    let client = Client::builder()
        .timeout(std::time::Duration::from_secs(2))
        .build()?;
        
    let results = Arc::new(Mutex::new(Vec::new()));
    
    // Concurrently test mirrors
    let stream = stream::iter(mirrors.clone())
        .map(|url| {
            let client = client.clone();
            let pb = pb.clone();
            let results = results.clone();
            async move {
                let start = Instant::now();
                // Just try to fetch the root or a small file to test connection
                // Standard arch mirrors structure: .../$repo/os/$arch
                // We'll try to connect to the base URL
                let test_url = url.replace("$repo", "core").replace("$arch", "x86_64");
                
                if client.head(&test_url).send().await.is_ok() {
                    let duration = start.elapsed();
                    let mut r = results.lock().unwrap();
                    r.push((url, duration));
                }
                pb.inc(1);
            }
        })
        .buffer_unordered(20); // Test 20 mirrors at a time
        
    stream.collect::<Vec<_>>().await;
    
    pb.finish_with_message("done");
    
    let mut ranked = results.lock().unwrap().clone();
    ranked.sort_by_key(|k| k.1);
    
    if ranked.is_empty() {
        return Err(anyhow!("all mirrors failed to respond"));
    }
    
    println!("{}", style(":: top 5 fastest mirrors:").bold().green());
    for (i, (url, duration)) in ranked.iter().take(5).enumerate() {
        println!("   {}. {} ({:?})", i + 1, url, duration);
    }
    
    // Backup
    let backup_path = format!("{}.backup", mirrorlist_path);
    fs::copy(mirrorlist_path, &backup_path)?;
    println!(":: backup created at {}", backup_path);
    
    // Write new mirrorlist
    let mut new_content = String::from("## Generated by pacboost\n");
    for (url, _) in ranked.iter().take(top) {
        new_content.push_str(&format!("Server = {}\n", url));
    }
    
    // Check for root before writing
    if unsafe { libc::geteuid() } != 0 {
         return Err(anyhow!("root privileges required to write to /etc/pacman.d/mirrorlist"));
    }
    
    fs::write(mirrorlist_path, new_content)?;
    println!("{}", style(":: mirrorlist updated successfully.").green().bold());
    
    Ok(())
}
